import type { ThemeColors, ThemePreset, ThemeTypography } from "./types";

const baseTypography = (scale: ThemeTypography["scale"] = "comfortable"): ThemeTypography => ({
  fontFamilyAr: "Tajawal, system-ui, sans-serif",
  fontFamilyEn: "Inter, system-ui, sans-serif",
  headingWeight: 800,
  bodyWeight: 500,
  scale,
});

function colors(partial: Partial<ThemeColors> & Pick<ThemeColors, "primary" | "accent">): ThemeColors {
  return {
    background: "#fafafa",
    foreground: "#18181b",
    card: "#ffffff",
    border: "#e4e4e7",
    muted: "#f4f4f5",
    mutedForeground: "#71717a",
    ...partial,
  };
}

function p(
  base: Omit<ThemePreset, "sortOrder"> & { sortOrder?: number },
  sortOrder: number,
): ThemePreset {
  return { ...base, sortOrder };
}

/** MVP catalog: 10 automotive + 10 general (expandable to 100+). */
export const THEME_PRESETS: ThemePreset[] = [
  // ── Automotive (10) ──
  p({
    id: "auto-luxury-showroom",
    nameAr: "معرض سيارات فاخر",
    nameEn: "Luxury Showroom",
    market: "automotive",
    category: "cars_luxury",
    previewStyle: "luxury-dark",
    colors: colors({ primary: "#111827", accent: "#b99a4a", background: "#080b12", foreground: "#f8fafc", card: "#121826", border: "#2f3848", muted: "#1f2937", mutedForeground: "#a7b0bf" }),
    typography: baseTypography("display"),
    headerStyle: "showroom-wide",
    productCardStyle: "luxury-tall",
    heroStyle: "spotlight",
    enabledSections: ["hero", "featured_products", "categories", "trust_badges", "whatsapp_cta"],
    suitableFor: ["معارض فاخرة", "سيارات فارهة", "وكالات راقية"],
  }, 1),
  p({
    id: "auto-sport-performance",
    nameAr: "سيارات رياضية",
    nameEn: "Sport Performance",
    market: "automotive",
    category: "cars_sport",
    previewStyle: "sport-red",
    colors: colors({ primary: "#c1121f", accent: "#111827", background: "#0b0f16", foreground: "#f9fafb", card: "#161b24", border: "#303746", muted: "#202735", mutedForeground: "#a8b0bd" }),
    typography: baseTypography("compact"),
    headerStyle: "split-nav",
    productCardStyle: "highlight-price",
    heroStyle: "neon",
    enabledSections: ["hero", "featured_products", "specs_strip", "categories"],
    suitableFor: ["رياضية", "تعديل", "أداء عالي"],
  }, 2),
  p({
    id: "auto-economy-value",
    nameAr: "سيارات اقتصادية",
    nameEn: "Economy Value",
    market: "automotive",
    category: "cars_economy",
    previewStyle: "clean-light",
    colors: colors({ primary: "#0f6c8f", accent: "#0f9f72", background: "#f7faf9", foreground: "#13202a", card: "#ffffff", border: "#d9e5e7", muted: "#edf5f3", mutedForeground: "#64727d" }),
    typography: baseTypography(),
    headerStyle: "minimal-sticky",
    productCardStyle: "flat-grid",
    heroStyle: "mesh",
    enabledSections: ["hero", "featured_products", "filters", "categories"],
    suitableFor: ["اقتصادية", "عائلات", "أول سيارة"],
  }, 3),
  p({
    id: "auto-parts-garage",
    nameAr: "قطع غيار",
    nameEn: "Parts & Garage",
    market: "automotive",
    category: "spare_parts",
    previewStyle: "industrial",
    colors: colors({ primary: "#214f78", accent: "#d58a11", background: "#f8fafc", foreground: "#172033", card: "#ffffff", border: "#d7dde6", muted: "#eef4f8", mutedForeground: "#5f6f80" }),
    typography: baseTypography("compact"),
    headerStyle: "split-nav",
    productCardStyle: "compact-dense",
    heroStyle: "aurora",
    enabledSections: ["hero", "categories", "featured_products", "search_prominent"],
    suitableFor: ["قطع غيار", "ورش", "مستودعات"],
  }, 4),
  p({
    id: "auto-accessories-hub",
    nameAr: "إكسسوارات سيارات",
    nameEn: "Car Accessories",
    market: "automotive",
    category: "car_accessories",
    previewStyle: "warm-retail",
    colors: colors({ primary: "#335c67", accent: "#d36b35", background: "#fbfaf7", foreground: "#1f2933", card: "#ffffff", border: "#e4ded5", muted: "#f3eee6", mutedForeground: "#71685f" }),
    typography: baseTypography(),
    headerStyle: "centered-logo",
    productCardStyle: "rounded-shadow",
    heroStyle: "silk",
    enabledSections: ["hero", "featured_products", "categories", "bundles"],
    suitableFor: ["إكسسوارات", "عناية بالسيارة", "تجهيزات"],
  }, 5),
  p({
    id: "auto-classic-heritage",
    nameAr: "سيارات كلاسيكية",
    nameEn: "Classic Heritage",
    market: "automotive",
    category: "cars_classic",
    previewStyle: "luxury-dark",
    colors: colors({ primary: "#d97706", accent: "#fbbf24", background: "#1c1917", foreground: "#fafaf9", card: "#292524", border: "#57534e", muted: "#44403c", mutedForeground: "#a8a29e" }),
    typography: baseTypography("display"),
    headerStyle: "boutique-compact",
    productCardStyle: "luxury-tall",
    heroStyle: "spotlight",
    enabledSections: ["hero", "story", "featured_products", "trust_badges"],
    suitableFor: ["كلاسيك", "ترميم", "مجموعات نادرة"],
  }, 6),
  p({
    id: "auto-trucks-equipment",
    nameAr: "شاحنات ومعدات",
    nameEn: "Trucks & Equipment",
    market: "automotive",
    category: "trucks",
    previewStyle: "industrial",
    colors: colors({ primary: "#1f4d36", accent: "#c95f22", background: "#f7f9f6", foreground: "#14221b", card: "#ffffff", border: "#dbe5dd", muted: "#edf3ee", mutedForeground: "#667468" }),
    typography: baseTypography("compact"),
    headerStyle: "showroom-wide",
    productCardStyle: "flat-grid",
    heroStyle: "aurora",
    enabledSections: ["hero", "categories", "featured_products", "specs_strip"],
    suitableFor: ["شاحنات", "معدات ثقيلة", "نقل تجاري"],
  }, 7),
  p({
    id: "auto-caravan-travel",
    nameAr: "كرفانات ورحلات",
    nameEn: "Caravan & Travel",
    market: "automotive",
    category: "caravans",
    previewStyle: "warm-retail",
    colors: colors({ primary: "#19786f", accent: "#d9772f", background: "#f9fbf8", foreground: "#1a2b2a", card: "#ffffff", border: "#dfe7df", muted: "#eef5ef", mutedForeground: "#66756f" }),
    typography: baseTypography("comfortable"),
    headerStyle: "centered-logo",
    productCardStyle: "rounded-shadow",
    heroStyle: "mesh",
    enabledSections: ["hero", "featured_products", "gallery", "whatsapp_cta"],
    suitableFor: ["كرفانات", "رحلات", "تخييم فاخر"],
  }, 8),
  p({
    id: "auto-official-dealer",
    nameAr: "وكالة رسمية",
    nameEn: "Official Dealer",
    market: "automotive",
    category: "dealer_oem",
    previewStyle: "clean-light",
    colors: colors({ primary: "#1d4f8f", accent: "#7b8794", background: "#f8fafc", foreground: "#172033", card: "#ffffff", border: "#d8e1eb", muted: "#eef3f8", mutedForeground: "#607083" }),
    typography: baseTypography(),
    headerStyle: "split-nav",
    productCardStyle: "highlight-price",
    heroStyle: "showroom-banner",
    enabledSections: ["hero", "brands_strip", "featured_products", "services", "trust_badges"],
    suitableFor: ["وكالات", "معتمد", "ضمان مصنع"],
  }, 9),
  p({
    id: "auto-service-deals",
    nameAr: "عروض وصيانة سيارات",
    nameEn: "Service & Deals",
    market: "automotive",
    category: "service_offers",
    previewStyle: "sport-red",
    colors: colors({ primary: "#b4232a", accent: "#283548", background: "#fbf8f7", foreground: "#1f242d", card: "#ffffff", border: "#eadfdd", muted: "#f5eeee", mutedForeground: "#706567" }),
    typography: baseTypography("compact"),
    headerStyle: "minimal-sticky",
    productCardStyle: "compact-dense",
    heroStyle: "neon",
    enabledSections: ["hero", "promo_banner", "featured_products", "booking_cta"],
    suitableFor: ["صيانة", "باقات", "عروض موسمية"],
  }, 10),

  // ── General retail (10) ──
  p({
    id: "retail-perfume-luxury",
    nameAr: "عطور فاخرة",
    nameEn: "Luxury Perfume",
    market: "general",
    category: "perfume",
    previewStyle: "minimal-boutique",
    colors: colors({ primary: "#34213d", accent: "#b8944d", background: "#fbf8f3", foreground: "#221d2a", card: "#ffffff", border: "#e8dfd0", muted: "#f4efe6", mutedForeground: "#746b62" }),
    typography: baseTypography("display"),
    headerStyle: "boutique-compact",
    productCardStyle: "luxury-tall",
    heroStyle: "silk",
    enabledSections: ["hero", "collections", "featured_products", "story"],
    suitableFor: ["عطور", "عود", "هدايا فاخرة"],
  }, 11),
  p({
    id: "retail-incense-oud",
    nameAr: "بخور وعود",
    nameEn: "Incense & Oud",
    market: "general",
    category: "incense",
    previewStyle: "warm-retail",
    colors: colors({ primary: "#4a2c1a", accent: "#9a6a2f", background: "#fbf6ee", foreground: "#2b2118", card: "#ffffff", border: "#eadfce", muted: "#f4eadb", mutedForeground: "#786b5b" }),
    typography: baseTypography("comfortable"),
    headerStyle: "centered-logo",
    productCardStyle: "rounded-shadow",
    heroStyle: "aurora",
    enabledSections: ["hero", "categories", "featured_products", "gift_sets"],
    suitableFor: ["بخور", "عود", "دهن عود"],
  }, 12),
  p({
    id: "retail-personal-accessories",
    nameAr: "إكسسوارات شخصية",
    nameEn: "Personal Accessories",
    market: "general",
    category: "accessories",
    previewStyle: "minimal-boutique",
    colors: colors({ primary: "#24242a", accent: "#b65a7a", background: "#fafafa", foreground: "#1d1d22", card: "#ffffff", border: "#e3e1df", muted: "#f3f2f1", mutedForeground: "#6f6a67" }),
    typography: baseTypography(),
    headerStyle: "minimal-sticky",
    productCardStyle: "rounded-shadow",
    heroStyle: "mesh",
    enabledSections: ["hero", "featured_products", "categories", "new_arrivals"],
    suitableFor: ["حقائب", "ساعات", "إكسسوارات"],
  }, 13),
  p({
    id: "retail-fashion-abaya",
    nameAr: "ملابس وثياب",
    nameEn: "Fashion & Abaya",
    market: "general",
    category: "fashion",
    previewStyle: "minimal-boutique",
    colors: colors({ primary: "#2c323b", accent: "#9a8f82", background: "#fbfbfa", foreground: "#171b21", card: "#ffffff", border: "#e2dfd9", muted: "#f4f2ee", mutedForeground: "#6c6861" }),
    typography: baseTypography("comfortable"),
    headerStyle: "boutique-compact",
    productCardStyle: "luxury-tall",
    heroStyle: "silk",
    enabledSections: ["hero", "collections", "featured_products", "size_guide"],
    suitableFor: ["ثياب", "عبايات", "أزياء"],
  }, 14),
  p({
    id: "retail-kids-wear",
    nameAr: "ملابس أطفال",
    nameEn: "Kids Wear",
    market: "general",
    category: "kids",
    previewStyle: "playful-kids",
    colors: colors({ primary: "#2f6f8f", accent: "#db7a9b", background: "#f7fbfd", foreground: "#172033", card: "#ffffff", border: "#dbe8ef", muted: "#edf6fa", mutedForeground: "#667783" }),
    typography: baseTypography("comfortable"),
    headerStyle: "centered-logo",
    productCardStyle: "rounded-shadow",
    heroStyle: "mesh",
    enabledSections: ["hero", "age_groups", "featured_products", "bundles"],
    suitableFor: ["أطفال", "رضع", "مدارس"],
  }, 15),
  p({
    id: "retail-jewelry",
    nameAr: "مجوهرات",
    nameEn: "Jewelry",
    market: "general",
    category: "jewelry",
    previewStyle: "jewel-gold",
    colors: colors({ primary: "#171513", accent: "#c9a24d", background: "#0d0b09", foreground: "#faf8f3", card: "#1a1714", border: "#443c32", muted: "#29241e", mutedForeground: "#b2a796" }),
    typography: baseTypography("display"),
    headerStyle: "boutique-compact",
    productCardStyle: "luxury-tall",
    heroStyle: "spotlight",
    enabledSections: ["hero", "collections", "featured_products", "certificates"],
    suitableFor: ["ذهب", "فضة", "الماس"],
  }, 16),
  p({
    id: "retail-gifts-packaging",
    nameAr: "هدايا وتغليف",
    nameEn: "Gifts & Packaging",
    market: "general",
    category: "gifts",
    previewStyle: "warm-retail",
    colors: colors({ primary: "#a13d62", accent: "#24948a", background: "#fbf7f7", foreground: "#241c22", card: "#ffffff", border: "#eadde2", muted: "#f4ecef", mutedForeground: "#75666c" }),
    typography: baseTypography(),
    headerStyle: "centered-logo",
    productCardStyle: "rounded-shadow",
    heroStyle: "silk",
    enabledSections: ["hero", "occasions", "featured_products", "custom_message"],
    suitableFor: ["هدايا", "تغليف", "مناسبات"],
  }, 17),
  p({
    id: "retail-home-living",
    nameAr: "منتجات منزلية",
    nameEn: "Home & Living",
    market: "general",
    category: "home",
    previewStyle: "clean-light",
    colors: colors({ primary: "#2b7068", accent: "#bd7f2d", background: "#faf9f5", foreground: "#1d2826", card: "#ffffff", border: "#e2ded4", muted: "#f1ede4", mutedForeground: "#6f6b62" }),
    typography: baseTypography(),
    headerStyle: "split-nav",
    productCardStyle: "flat-grid",
    heroStyle: "aurora",
    enabledSections: ["hero", "rooms", "featured_products", "categories"],
    suitableFor: ["منزل", "مطبخ", "ديكور"],
  }, 18),
  p({
    id: "retail-electronics-lite",
    nameAr: "إلكترونيات خفيفة",
    nameEn: "Light Electronics",
    market: "general",
    category: "electronics",
    previewStyle: "tech-slate",
    colors: colors({ primary: "#162033", accent: "#2d8db3", background: "#f8fafc", foreground: "#121b2c", card: "#ffffff", border: "#dbe3ec", muted: "#edf2f7", mutedForeground: "#617080" }),
    typography: baseTypography("compact"),
    headerStyle: "split-nav",
    productCardStyle: "highlight-price",
    heroStyle: "neon",
    enabledSections: ["hero", "featured_products", "specs_strip", "warranty"],
    suitableFor: ["جوالات", "إكسسوارات تقنية", "سماعات"],
  }, 19),
  p({
    id: "retail-multi-department",
    nameAr: "متجر عام متعدد الأقسام",
    nameEn: "Multi-Department Store",
    market: "mixed",
    category: "general_store",
    previewStyle: "marketplace-grid",
    colors: colors({ primary: "#15846f", accent: "#2d6f9f", background: "#f8fbfa", foreground: "#152421", card: "#ffffff", border: "#dbe7e4", muted: "#edf5f2", mutedForeground: "#63736f" }),
    typography: baseTypography(),
    headerStyle: "split-nav",
    productCardStyle: "flat-grid",
    heroStyle: "mesh",
    enabledSections: ["hero", "departments", "featured_products", "categories", "promo_banner"],
    suitableFor: ["متنوع", "سوبر ماركت صغير", "كل الفئات"],
  }, 20),
];

export const THEME_PRESET_MAP = Object.fromEntries(
  THEME_PRESETS.map((t) => [t.id, t]),
) as Record<string, ThemePreset>;

export function getThemePreset(id: string | null | undefined): ThemePreset | undefined {
  if (!id) return undefined;
  return THEME_PRESET_MAP[id];
}

export function listPresetsByMarket(market?: "automotive" | "general" | "all"): ThemePreset[] {
  if (!market || market === "all") return THEME_PRESETS;
  return THEME_PRESETS.filter((t) => t.market === market || t.market === "mixed");
}
