import type { ThemeColors, ThemePreset, ThemeTypography } from "./types";

const baseTypography = (scale: ThemeTypography["scale"] = "comfortable"): ThemeTypography => ({
  fontFamilyAr: "Tajawal, system-ui, sans-serif",
  fontFamilyEn: "Inter, system-ui, sans-serif",
  headingWeight: 800,
  bodyWeight: 500,
  scale,
});

function colors(partial: Partial<ThemeColors> & Pick<ThemeColors, "primary" | "accent">): ThemeColors {
  return {
    background: "#fafafa",
    foreground: "#18181b",
    card: "#ffffff",
    border: "#e4e4e7",
    muted: "#f4f4f5",
    mutedForeground: "#71717a",
    ...partial,
  };
}

function p(
  base: Omit<ThemePreset, "sortOrder"> & { sortOrder?: number },
  sortOrder: number,
): ThemePreset {
  return { ...base, sortOrder };
}

/** MVP catalog: 10 automotive + 10 general (expandable to 100+). */
export const THEME_PRESETS: ThemePreset[] = [
  // ── Automotive (10) ──
  p({
    id: "auto-luxury-showroom",
    nameAr: "معرض سيارات فاخر",
    nameEn: "Luxury Showroom",
    market: "automotive",
    category: "cars_luxury",
    previewStyle: "luxury-dark",
    colors: colors({ primary: "#0f172a", accent: "#c9a227", background: "#0b1020", foreground: "#f8fafc", card: "#111827", border: "#334155", muted: "#1e293b", mutedForeground: "#94a3b8" }),
    typography: baseTypography("display"),
    headerStyle: "showroom-wide",
    productCardStyle: "luxury-tall",
    heroStyle: "spotlight",
    enabledSections: ["hero", "featured_products", "categories", "trust_badges", "whatsapp_cta"],
    suitableFor: ["معارض فاخرة", "سيارات فارهة", "وكالات premium"],
  }, 1),
  p({
    id: "auto-sport-performance",
    nameAr: "سيارات رياضية",
    nameEn: "Sport Performance",
    market: "automotive",
    category: "cars_sport",
    previewStyle: "sport-red",
    colors: colors({ primary: "#b91c1c", accent: "#1f2937", background: "#09090b", foreground: "#fafafa", card: "#18181b", border: "#3f3f46", muted: "#27272a", mutedForeground: "#a1a1aa" }),
    typography: baseTypography("compact"),
    headerStyle: "split-nav",
    productCardStyle: "highlight-price",
    heroStyle: "neon",
    enabledSections: ["hero", "featured_products", "specs_strip", "categories"],
    suitableFor: ["رياضية", "تعديل", "أداء عالي"],
  }, 2),
  p({
    id: "auto-economy-value",
    nameAr: "سيارات اقتصادية",
    nameEn: "Economy Value",
    market: "automotive",
    category: "cars_economy",
    previewStyle: "clean-light",
    colors: colors({ primary: "#0369a1", accent: "#059669" }),
    typography: baseTypography(),
    headerStyle: "minimal-sticky",
    productCardStyle: "flat-grid",
    heroStyle: "mesh",
    enabledSections: ["hero", "featured_products", "filters", "categories"],
    suitableFor: ["اقتصادية", "عائلات", "أول سيارة"],
  }, 3),
  p({
    id: "auto-parts-garage",
    nameAr: "قطع غيار",
    nameEn: "Parts & Garage",
    market: "automotive",
    category: "spare_parts",
    previewStyle: "industrial",
    colors: colors({ primary: "#1d4ed8", accent: "#f59e0b", muted: "#eff6ff" }),
    typography: baseTypography("compact"),
    headerStyle: "split-nav",
    productCardStyle: "compact-dense",
    heroStyle: "aurora",
    enabledSections: ["hero", "categories", "featured_products", "search_prominent"],
    suitableFor: ["قطع غيار", "ورش", "مستودعات"],
  }, 4),
  p({
    id: "auto-accessories-hub",
    nameAr: "إكسسوارات سيارات",
    nameEn: "Car Accessories",
    market: "automotive",
    category: "car_accessories",
    previewStyle: "warm-retail",
    colors: colors({ primary: "#7c3aed", accent: "#06b6d4" }),
    typography: baseTypography(),
    headerStyle: "centered-logo",
    productCardStyle: "rounded-shadow",
    heroStyle: "silk",
    enabledSections: ["hero", "featured_products", "categories", "bundles"],
    suitableFor: ["إكسسوارات", "عناية بالسيارة", "تجهيزات"],
  }, 5),
  p({
    id: "auto-classic-heritage",
    nameAr: "سيارات كلاسيكية",
    nameEn: "Classic Heritage",
    market: "automotive",
    category: "cars_classic",
    previewStyle: "luxury-dark",
    colors: colors({ primary: "#d97706", accent: "#fbbf24", background: "#1c1917", foreground: "#fafaf9", card: "#292524", border: "#57534e", muted: "#44403c", mutedForeground: "#a8a29e" }),
    typography: baseTypography("display"),
    headerStyle: "boutique-compact",
    productCardStyle: "luxury-tall",
    heroStyle: "spotlight",
    enabledSections: ["hero", "story", "featured_products", "trust_badges"],
    suitableFor: ["كلاسيك", "ترميم", "مجموعات نادرة"],
  }, 6),
  p({
    id: "auto-trucks-equipment",
    nameAr: "شاحنات ومعدات",
    nameEn: "Trucks & Equipment",
    market: "automotive",
    category: "trucks",
    previewStyle: "industrial",
    colors: colors({ primary: "#14532d", accent: "#ea580c" }),
    typography: baseTypography("compact"),
    headerStyle: "showroom-wide",
    productCardStyle: "flat-grid",
    heroStyle: "aurora",
    enabledSections: ["hero", "categories", "featured_products", "specs_strip"],
    suitableFor: ["شاحنات", "معدات ثقيلة", "نقل تجاري"],
  }, 7),
  p({
    id: "auto-caravan-travel",
    nameAr: "كرفانات ورحلات",
    nameEn: "Caravan & Travel",
    market: "automotive",
    category: "caravans",
    previewStyle: "warm-retail",
    colors: colors({ primary: "#0d9488", accent: "#f97316" }),
    typography: baseTypography("comfortable"),
    headerStyle: "centered-logo",
    productCardStyle: "rounded-shadow",
    heroStyle: "mesh",
    enabledSections: ["hero", "featured_products", "gallery", "whatsapp_cta"],
    suitableFor: ["كرفانات", "رحلات", "تخييم فاخر"],
  }, 8),
  p({
    id: "auto-official-dealer",
    nameAr: "وكالة رسمية",
    nameEn: "Official Dealer",
    market: "automotive",
    category: "dealer_oem",
    previewStyle: "clean-light",
    colors: colors({ primary: "#1e3a8a", accent: "#64748b", card: "#ffffff" }),
    typography: baseTypography(),
    headerStyle: "split-nav",
    productCardStyle: "highlight-price",
    heroStyle: "showroom-banner",
    enabledSections: ["hero", "brands_strip", "featured_products", "services", "trust_badges"],
    suitableFor: ["وكالات", "معتمد", "ضمان مصنع"],
  }, 9),
  p({
    id: "auto-service-deals",
    nameAr: "عروض وصيانة سيارات",
    nameEn: "Service & Deals",
    market: "automotive",
    category: "service_offers",
    previewStyle: "sport-red",
    colors: colors({ primary: "#dc2626", accent: "#111827" }),
    typography: baseTypography("compact"),
    headerStyle: "minimal-sticky",
    productCardStyle: "compact-dense",
    heroStyle: "neon",
    enabledSections: ["hero", "promo_banner", "featured_products", "booking_cta"],
    suitableFor: ["صيانة", "باقات", "عروض موسمية"],
  }, 10),

  // ── General retail (10) ──
  p({
    id: "retail-perfume-luxury",
    nameAr: "عطور فاخرة",
    nameEn: "Luxury Perfume",
    market: "general",
    category: "perfume",
    previewStyle: "minimal-boutique",
    colors: colors({ primary: "#4c1d95", accent: "#d4af37", background: "#faf5ff", foreground: "#1e1b4b", card: "#ffffff", border: "#e9d5ff", muted: "#f5f3ff", mutedForeground: "#6b7280" }),
    typography: baseTypography("display"),
    headerStyle: "boutique-compact",
    productCardStyle: "luxury-tall",
    heroStyle: "silk",
    enabledSections: ["hero", "collections", "featured_products", "story"],
    suitableFor: ["عطور", "عود", "هدايا فاخرة"],
  }, 11),
  p({
    id: "retail-incense-oud",
    nameAr: "بخور وعود",
    nameEn: "Incense & Oud",
    market: "general",
    category: "incense",
    previewStyle: "warm-retail",
    colors: colors({ primary: "#78350f", accent: "#b45309", background: "#fffbeb", foreground: "#292524", muted: "#fef3c7" }),
    typography: baseTypography("comfortable"),
    headerStyle: "centered-logo",
    productCardStyle: "rounded-shadow",
    heroStyle: "aurora",
    enabledSections: ["hero", "categories", "featured_products", "gift_sets"],
    suitableFor: ["بخور", "عود", "دهن عود"],
  }, 12),
  p({
    id: "retail-personal-accessories",
    nameAr: "إكسسوارات شخصية",
    nameEn: "Personal Accessories",
    market: "general",
    category: "accessories",
    previewStyle: "minimal-boutique",
    colors: colors({ primary: "#18181b", accent: "#ec4899" }),
    typography: baseTypography(),
    headerStyle: "minimal-sticky",
    productCardStyle: "rounded-shadow",
    heroStyle: "mesh",
    enabledSections: ["hero", "featured_products", "categories", "new_arrivals"],
    suitableFor: ["حقائب", "ساعات", "إكسسوارات"],
  }, 13),
  p({
    id: "retail-fashion-abaya",
    nameAr: "ملابس وثياب",
    nameEn: "Fashion & Abaya",
    market: "general",
    category: "fashion",
    previewStyle: "minimal-boutique",
    colors: colors({ primary: "#1f2937", accent: "#9ca3af", background: "#ffffff", foreground: "#111827", muted: "#f9fafb" }),
    typography: baseTypography("comfortable"),
    headerStyle: "boutique-compact",
    productCardStyle: "luxury-tall",
    heroStyle: "silk",
    enabledSections: ["hero", "collections", "featured_products", "size_guide"],
    suitableFor: ["ثياب", "عبايات", "أزياء"],
  }, 14),
  p({
    id: "retail-kids-wear",
    nameAr: "ملابس أطفال",
    nameEn: "Kids Wear",
    market: "general",
    category: "kids",
    previewStyle: "playful-kids",
    colors: colors({ primary: "#2563eb", accent: "#f472b6", background: "#f0f9ff", foreground: "#0f172a", muted: "#e0f2fe" }),
    typography: baseTypography("comfortable"),
    headerStyle: "centered-logo",
    productCardStyle: "rounded-shadow",
    heroStyle: "mesh",
    enabledSections: ["hero", "age_groups", "featured_products", "bundles"],
    suitableFor: ["أطفال", "رضع", "مدارس"],
  }, 15),
  p({
    id: "retail-jewelry",
    nameAr: "مجوهرات",
    nameEn: "Jewelry",
    market: "general",
    category: "jewelry",
    previewStyle: "jewel-gold",
    colors: colors({ primary: "#1c1917", accent: "#eab308", background: "#0c0a09", foreground: "#fafaf9", card: "#1c1917", border: "#44403c", muted: "#292524", mutedForeground: "#a8a29e" }),
    typography: baseTypography("display"),
    headerStyle: "boutique-compact",
    productCardStyle: "luxury-tall",
    heroStyle: "spotlight",
    enabledSections: ["hero", "collections", "featured_products", "certificates"],
    suitableFor: ["ذهب", "فضة", "الماس"],
  }, 16),
  p({
    id: "retail-gifts-packaging",
    nameAr: "هدايا وتغليف",
    nameEn: "Gifts & Packaging",
    market: "general",
    category: "gifts",
    previewStyle: "warm-retail",
    colors: colors({ primary: "#be185d", accent: "#14b8a6" }),
    typography: baseTypography(),
    headerStyle: "centered-logo",
    productCardStyle: "rounded-shadow",
    heroStyle: "silk",
    enabledSections: ["hero", "occasions", "featured_products", "custom_message"],
    suitableFor: ["هدايا", "تغليف", "مناسبات"],
  }, 17),
  p({
    id: "retail-home-living",
    nameAr: "منتجات منزلية",
    nameEn: "Home & Living",
    market: "general",
    category: "home",
    previewStyle: "clean-light",
    colors: colors({ primary: "#0f766e", accent: "#f59e0b" }),
    typography: baseTypography(),
    headerStyle: "split-nav",
    productCardStyle: "flat-grid",
    heroStyle: "aurora",
    enabledSections: ["hero", "rooms", "featured_products", "categories"],
    suitableFor: ["منزل", "مطبخ", "ديكور"],
  }, 18),
  p({
    id: "retail-electronics-lite",
    nameAr: "إلكترونيات خفيفة",
    nameEn: "Light Electronics",
    market: "general",
    category: "electronics",
    previewStyle: "tech-slate",
    colors: colors({ primary: "#0f172a", accent: "#38bdf8", background: "#f8fafc", foreground: "#0f172a", muted: "#e2e8f0" }),
    typography: baseTypography("compact"),
    headerStyle: "split-nav",
    productCardStyle: "highlight-price",
    heroStyle: "neon",
    enabledSections: ["hero", "featured_products", "specs_strip", "warranty"],
    suitableFor: ["جوالات", "إكسسوارات تقنية", "سماعات"],
  }, 19),
  p({
    id: "retail-multi-department",
    nameAr: "متجر عام متعدد الأقسام",
    nameEn: "Multi-Department Store",
    market: "mixed",
    category: "general_store",
    previewStyle: "marketplace-grid",
    colors: colors({ primary: "#059669", accent: "#0284c7" }),
    typography: baseTypography(),
    headerStyle: "split-nav",
    productCardStyle: "flat-grid",
    heroStyle: "mesh",
    enabledSections: ["hero", "departments", "featured_products", "categories", "promo_banner"],
    suitableFor: ["متنوع", "سوبر ماركت صغير", "كل الفئات"],
  }, 20),
];

export const THEME_PRESET_MAP = Object.fromEntries(
  THEME_PRESETS.map((t) => [t.id, t]),
) as Record<string, ThemePreset>;

export function getThemePreset(id: string | null | undefined): ThemePreset | undefined {
  if (!id) return undefined;
  return THEME_PRESET_MAP[id];
}

export function listPresetsByMarket(market?: "automotive" | "general" | "all"): ThemePreset[] {
  if (!market || market === "all") return THEME_PRESETS;
  return THEME_PRESETS.filter((t) => t.market === market || t.market === "mixed");
}
