import type { ThemeColors, ThemePreset, ThemeTypography } from "./types";

const baseTypography = (scale: ThemeTypography["scale"] = "comfortable"): ThemeTypography => ({
  fontFamilyAr: "Tajawal, system-ui, sans-serif",
  fontFamilyEn: "Inter, system-ui, sans-serif",
  headingWeight: 800,
  bodyWeight: 500,
  scale,
});

function colors(partial: Partial<ThemeColors> & Pick<ThemeColors, "primary" | "accent">): ThemeColors {
  return {
    background: "#fafafa",
    foreground: "#18181b",
    card: "#ffffff",
    border: "#e4e4e7",
    muted: "#f4f4f5",
    mutedForeground: "#71717a",
    ...partial,
  };
}

function p(
  base: Omit<ThemePreset, "sortOrder"> & { sortOrder?: number },
  sortOrder: number,
): ThemePreset {
  return { ...base, sortOrder };
}

/** Theme catalog: automotive + retail presets (expandable to 100+). */
export const THEME_PRESETS: ThemePreset[] = [
  // ── Automotive (10) ──
  p({
    id: "auto-luxury-showroom",
    nameAr: "معرض سيارات فاخر",
    nameEn: "Luxury Showroom",
    market: "automotive",
    category: "cars_luxury",
    previewStyle: "luxury-dark",
    colors: colors({ primary: "#0f172a", accent: "#c9a227", background: "#0b1020", foreground: "#f8fafc", card: "#111827", border: "#334155", muted: "#1e293b", mutedForeground: "#94a3b8" }),
    typography: baseTypography("display"),
    headerStyle: "showroom-wide",
    productCardStyle: "luxury-tall",
    heroStyle: "spotlight",
    enabledSections: ["hero", "featured_products", "categories", "trust_badges", "whatsapp_cta"],
    suitableFor: ["معارض فاخرة", "سيارات فارهة", "وكالات premium"],
  }, 1),
  p({
    id: "auto-sport-performance",
    nameAr: "سيارات رياضية",
    nameEn: "Sport Performance",
    market: "automotive",
    category: "cars_sport",
    previewStyle: "sport-red",
    colors: colors({ primary: "#b91c1c", accent: "#1f2937", background: "#09090b", foreground: "#fafafa", card: "#18181b", border: "#3f3f46", muted: "#27272a", mutedForeground: "#a1a1aa" }),
    typography: baseTypography("compact"),
    headerStyle: "split-nav",
    productCardStyle: "highlight-price",
    heroStyle: "neon",
    enabledSections: ["hero", "featured_products", "specs_strip", "categories"],
    suitableFor: ["رياضية", "تعديل", "أداء عالي"],
  }, 2),
  p({
    id: "auto-economy-value",
    nameAr: "سيارات اقتصادية",
    nameEn: "Economy Value",
    market: "automotive",
    category: "cars_economy",
    previewStyle: "clean-light",
    colors: colors({ primary: "#0369a1", accent: "#059669" }),
    typography: baseTypography(),
    headerStyle: "minimal-sticky",
    productCardStyle: "flat-grid",
    heroStyle: "mesh",
    enabledSections: ["hero", "featured_products", "filters", "categories"],
    suitableFor: ["اقتصادية", "عائلات", "أول سيارة"],
  }, 3),
  p({
    id: "auto-parts-garage",
    nameAr: "قطع غيار",
    nameEn: "Parts & Garage",
    market: "automotive",
    category: "spare_parts",
    previewStyle: "industrial",
    colors: colors({ primary: "#1d4ed8", accent: "#f59e0b", muted: "#eff6ff" }),
    typography: baseTypography("compact"),
    headerStyle: "split-nav",
    productCardStyle: "compact-dense",
    heroStyle: "aurora",
    enabledSections: ["hero", "categories", "featured_products", "search_prominent"],
    suitableFor: ["قطع غيار", "ورش", "مستودعات"],
  }, 4),
  p({
    id: "auto-accessories-hub",
    nameAr: "إكسسوارات سيارات",
    nameEn: "Car Accessories",
    market: "automotive",
    category: "car_accessories",
    previewStyle: "warm-retail",
    colors: colors({ primary: "#7c3aed", accent: "#06b6d4" }),
    typography: baseTypography(),
    headerStyle: "centered-logo",
    productCardStyle: "rounded-shadow",
    heroStyle: "silk",
    enabledSections: ["hero", "featured_products", "categories", "bundles"],
    suitableFor: ["إكسسوارات", "عناية بالسيارة", "تجهيزات"],
  }, 5),
  p({
    id: "auto-classic-heritage",
    nameAr: "سيارات كلاسيكية",
    nameEn: "Classic Heritage",
    market: "automotive",
    category: "cars_classic",
    previewStyle: "luxury-dark",
    colors: colors({ primary: "#d97706", accent: "#fbbf24", background: "#1c1917", foreground: "#fafaf9", card: "#292524", border: "#57534e", muted: "#44403c", mutedForeground: "#a8a29e" }),
    typography: baseTypography("display"),
    headerStyle: "boutique-compact",
    productCardStyle: "luxury-tall",
    heroStyle: "spotlight",
    enabledSections: ["hero", "story", "featured_products", "trust_badges"],
    suitableFor: ["كلاسيك", "ترميم", "مجموعات نادرة"],
  }, 6),
  p({
    id: "auto-trucks-equipment",
    nameAr: "شاحنات ومعدات",
    nameEn: "Trucks & Equipment",
    market: "automotive",
    category: "trucks",
    previewStyle: "industrial",
    colors: colors({ primary: "#14532d", accent: "#ea580c" }),
    typography: baseTypography("compact"),
    headerStyle: "showroom-wide",
    productCardStyle: "flat-grid",
    heroStyle: "aurora",
    enabledSections: ["hero", "categories", "featured_products", "specs_strip"],
    suitableFor: ["شاحنات", "معدات ثقيلة", "نقل تجاري"],
  }, 7),
  p({
    id: "auto-caravan-travel",
    nameAr: "كرفانات ورحلات",
    nameEn: "Caravan & Travel",
    market: "automotive",
    category: "caravans",
    previewStyle: "warm-retail",
    colors: colors({ primary: "#0d9488", accent: "#f97316" }),
    typography: baseTypography("comfortable"),
    headerStyle: "centered-logo",
    productCardStyle: "rounded-shadow",
    heroStyle: "mesh",
    enabledSections: ["hero", "featured_products", "gallery", "whatsapp_cta"],
    suitableFor: ["كرفانات", "رحلات", "تخييم فاخر"],
  }, 8),
  p({
    id: "auto-official-dealer",
    nameAr: "وكالة رسمية",
    nameEn: "Official Dealer",
    market: "automotive",
    category: "dealer_oem",
    previewStyle: "clean-light",
    colors: colors({ primary: "#1e3a8a", accent: "#64748b", card: "#ffffff" }),
    typography: baseTypography(),
    headerStyle: "split-nav",
    productCardStyle: "highlight-price",
    heroStyle: "showroom-banner",
    enabledSections: ["hero", "brands_strip", "featured_products", "services", "trust_badges"],
    suitableFor: ["وكالات", "معتمد", "ضمان مصنع"],
  }, 9),
  p({
    id: "auto-service-deals",
    nameAr: "عروض وصيانة سيارات",
    nameEn: "Service & Deals",
    market: "automotive",
    category: "service_offers",
    previewStyle: "sport-red",
    colors: colors({ primary: "#dc2626", accent: "#111827" }),
    typography: baseTypography("compact"),
    headerStyle: "minimal-sticky",
    productCardStyle: "compact-dense",
    heroStyle: "neon",
    enabledSections: ["hero", "promo_banner", "featured_products", "booking_cta"],
    suitableFor: ["صيانة", "باقات", "عروض موسمية"],
  }, 10),

  // ── General retail (10) ──
  p({
    id: "retail-perfume-luxury",
    nameAr: "عطور فاخرة",
    nameEn: "Luxury Perfume",
    market: "general",
    category: "perfume",
    previewStyle: "minimal-boutique",
    colors: colors({ primary: "#4c1d95", accent: "#d4af37", background: "#faf5ff", foreground: "#1e1b4b", card: "#ffffff", border: "#e9d5ff", muted: "#f5f3ff", mutedForeground: "#6b7280" }),
    typography: baseTypography("display"),
    headerStyle: "boutique-compact",
    productCardStyle: "luxury-tall",
    heroStyle: "silk",
    enabledSections: ["hero", "collections", "featured_products", "story"],
    suitableFor: ["عطور", "عود", "هدايا فاخرة"],
  }, 11),
  p({
    id: "retail-incense-oud",
    nameAr: "بخور وعود",
    nameEn: "Incense & Oud",
    market: "general",
    category: "incense",
    previewStyle: "warm-retail",
    colors: colors({ primary: "#78350f", accent: "#b45309", background: "#fffbeb", foreground: "#292524", muted: "#fef3c7" }),
    typography: baseTypography("comfortable"),
    headerStyle: "centered-logo",
    productCardStyle: "rounded-shadow",
    heroStyle: "aurora",
    enabledSections: ["hero", "categories", "featured_products", "gift_sets"],
    suitableFor: ["بخور", "عود", "دهن عود"],
  }, 12),
  p({
    id: "retail-personal-accessories",
    nameAr: "إكسسوارات شخصية",
    nameEn: "Personal Accessories",
    market: "general",
    category: "accessories",
    previewStyle: "minimal-boutique",
    colors: colors({ primary: "#18181b", accent: "#ec4899" }),
    typography: baseTypography(),
    headerStyle: "minimal-sticky",
    productCardStyle: "rounded-shadow",
    heroStyle: "mesh",
    enabledSections: ["hero", "featured_products", "categories", "new_arrivals"],
    suitableFor: ["حقائب", "ساعات", "إكسسوارات"],
  }, 13),
  p({
    id: "retail-fashion-abaya",
    nameAr: "ملابس وثياب",
    nameEn: "Fashion & Abaya",
    market: "general",
    category: "fashion",
    previewStyle: "minimal-boutique",
    colors: colors({ primary: "#1f2937", accent: "#9ca3af", background: "#ffffff", foreground: "#111827", muted: "#f9fafb" }),
    typography: baseTypography("comfortable"),
    headerStyle: "boutique-compact",
    productCardStyle: "luxury-tall",
    heroStyle: "silk",
    enabledSections: ["hero", "collections", "featured_products", "size_guide"],
    suitableFor: ["ثياب", "عبايات", "أزياء"],
  }, 14),
  p({
    id: "retail-kids-wear",
    nameAr: "ملابس أطفال",
    nameEn: "Kids Wear",
    market: "general",
    category: "kids",
    previewStyle: "playful-kids",
    colors: colors({ primary: "#2563eb", accent: "#f472b6", background: "#f0f9ff", foreground: "#0f172a", muted: "#e0f2fe" }),
    typography: baseTypography("comfortable"),
    headerStyle: "centered-logo",
    productCardStyle: "rounded-shadow",
    heroStyle: "mesh",
    enabledSections: ["hero", "age_groups", "featured_products", "bundles"],
    suitableFor: ["أطفال", "رضع", "مدارس"],
  }, 15),
  p({
    id: "retail-jewelry",
    nameAr: "مجوهرات",
    nameEn: "Jewelry",
    market: "general",
    category: "jewelry",
    previewStyle: "jewel-gold",
    colors: colors({ primary: "#1c1917", accent: "#eab308", background: "#0c0a09", foreground: "#fafaf9", card: "#1c1917", border: "#44403c", muted: "#292524", mutedForeground: "#a8a29e" }),
    typography: baseTypography("display"),
    headerStyle: "boutique-compact",
    productCardStyle: "luxury-tall",
    heroStyle: "spotlight",
    enabledSections: ["hero", "collections", "featured_products", "certificates"],
    suitableFor: ["ذهب", "فضة", "الماس"],
  }, 16),
  p({
    id: "retail-gifts-packaging",
    nameAr: "هدايا وتغليف",
    nameEn: "Gifts & Packaging",
    market: "general",
    category: "gifts",
    previewStyle: "warm-retail",
    colors: colors({ primary: "#be185d", accent: "#14b8a6" }),
    typography: baseTypography(),
    headerStyle: "centered-logo",
    productCardStyle: "rounded-shadow",
    heroStyle: "silk",
    enabledSections: ["hero", "occasions", "featured_products", "custom_message"],
    suitableFor: ["هدايا", "تغليف", "مناسبات"],
  }, 17),
  p({
    id: "retail-home-living",
    nameAr: "منتجات منزلية",
    nameEn: "Home & Living",
    market: "general",
    category: "home",
    previewStyle: "clean-light",
    colors: colors({ primary: "#0f766e", accent: "#f59e0b" }),
    typography: baseTypography(),
    headerStyle: "split-nav",
    productCardStyle: "flat-grid",
    heroStyle: "aurora",
    enabledSections: ["hero", "rooms", "featured_products", "categories"],
    suitableFor: ["منزل", "مطبخ", "ديكور"],
  }, 18),
  p({
    id: "retail-electronics-lite",
    nameAr: "إلكترونيات خفيفة",
    nameEn: "Light Electronics",
    market: "general",
    category: "electronics",
    previewStyle: "tech-slate",
    colors: colors({ primary: "#0f172a", accent: "#38bdf8", background: "#f8fafc", foreground: "#0f172a", muted: "#e2e8f0" }),
    typography: baseTypography("compact"),
    headerStyle: "split-nav",
    productCardStyle: "highlight-price",
    heroStyle: "neon",
    enabledSections: ["hero", "featured_products", "specs_strip", "warranty"],
    suitableFor: ["جوالات", "إكسسوارات تقنية", "سماعات"],
  }, 19),
  p({
    id: "retail-multi-department",
    nameAr: "متجر عام متعدد الأقسام",
    nameEn: "Multi-Department Store",
    market: "mixed",
    category: "general_store",
    previewStyle: "marketplace-grid",
    colors: colors({ primary: "#059669", accent: "#0284c7" }),
    typography: baseTypography(),
    headerStyle: "split-nav",
    productCardStyle: "flat-grid",
    heroStyle: "mesh",
    enabledSections: ["hero", "departments", "featured_products", "categories", "promo_banner"],
    suitableFor: ["متنوع", "سوبر ماركت صغير", "كل الفئات"],
  }, 20),

  // ── Expanded automotive (6) ──
  p({
    id: "auto-ev-future",
    nameAr: "سيارات كهربائية",
    nameEn: "EV Future",
    market: "automotive",
    category: "electric_vehicles",
    previewStyle: "tech-slate",
    colors: colors({ primary: "#047857", accent: "#38bdf8", background: "#ecfeff", foreground: "#083344", card: "#ffffff", border: "#bae6fd", muted: "#cffafe", mutedForeground: "#0e7490" }),
    typography: baseTypography("compact"),
    headerStyle: "minimal-sticky",
    productCardStyle: "highlight-price",
    heroStyle: "neon",
    enabledSections: ["hero", "featured_products", "charging_specs", "warranty", "trust_badges"],
    suitableFor: ["كهربائية", "هايبرد", "تقنيات شحن"],
  }, 21),
  p({
    id: "auto-rental-fleet",
    nameAr: "تأجير أسطول",
    nameEn: "Rental Fleet",
    market: "automotive",
    category: "rental",
    previewStyle: "clean-light",
    colors: colors({ primary: "#155e75", accent: "#f59e0b", background: "#f8fafc", foreground: "#0f172a", muted: "#e0f2fe" }),
    typography: baseTypography("comfortable"),
    headerStyle: "showroom-wide",
    productCardStyle: "flat-grid",
    heroStyle: "showroom-banner",
    enabledSections: ["hero", "fleet_filters", "featured_products", "booking_cta", "trust_badges"],
    suitableFor: ["تأجير يومي", "شركات", "أساطيل"],
  }, 22),
  p({
    id: "auto-motorcycle-street",
    nameAr: "دراجات ومحركات",
    nameEn: "Motorcycle Street",
    market: "automotive",
    category: "motorcycles",
    previewStyle: "sport-red",
    colors: colors({ primary: "#111827", accent: "#ef4444", background: "#0a0a0a", foreground: "#fafafa", card: "#18181b", border: "#3f3f46", muted: "#27272a", mutedForeground: "#a1a1aa" }),
    typography: baseTypography("display"),
    headerStyle: "split-nav",
    productCardStyle: "compact-dense",
    heroStyle: "neon",
    enabledSections: ["hero", "featured_products", "specs_strip", "gear_bundles"],
    suitableFor: ["دراجات", "خوذ", "إكسسوارات ركوب"],
  }, 23),
  p({
    id: "auto-detailing-spa",
    nameAr: "عناية وتلميع",
    nameEn: "Detailing Spa",
    market: "automotive",
    category: "detailing",
    previewStyle: "minimal-boutique",
    colors: colors({ primary: "#0f766e", accent: "#8b5cf6", background: "#f0fdfa", foreground: "#134e4a", card: "#ffffff", border: "#ccfbf1", muted: "#ecfeff" }),
    typography: baseTypography("comfortable"),
    headerStyle: "boutique-compact",
    productCardStyle: "rounded-shadow",
    heroStyle: "silk",
    enabledSections: ["hero", "service_packages", "featured_products", "before_after", "booking_cta"],
    suitableFor: ["تلميع", "حماية PPF", "غسيل فاخر"],
  }, 24),
  p({
    id: "auto-auction-lane",
    nameAr: "مزادات سيارات",
    nameEn: "Auction Lane",
    market: "automotive",
    category: "auction",
    previewStyle: "industrial",
    colors: colors({ primary: "#7f1d1d", accent: "#fbbf24", background: "#111827", foreground: "#f9fafb", card: "#1f2937", border: "#374151", muted: "#111827", mutedForeground: "#d1d5db" }),
    typography: baseTypography("compact"),
    headerStyle: "showroom-wide",
    productCardStyle: "highlight-price",
    heroStyle: "spotlight",
    enabledSections: ["hero", "live_lots", "featured_products", "bid_cta", "trust_badges"],
    suitableFor: ["مزادات", "فرص سريعة", "سيارات مستعملة"],
  }, 25),
  p({
    id: "auto-tires-battery",
    nameAr: "إطارات وبطاريات",
    nameEn: "Tires & Battery",
    market: "automotive",
    category: "tires_battery",
    previewStyle: "industrial",
    colors: colors({ primary: "#1f2937", accent: "#84cc16", background: "#f9fafb", foreground: "#111827", card: "#ffffff", border: "#d4d4d8", muted: "#f4f4f5" }),
    typography: baseTypography("compact"),
    headerStyle: "minimal-sticky",
    productCardStyle: "compact-dense",
    heroStyle: "aurora",
    enabledSections: ["hero", "size_finder", "featured_products", "fitment_notes", "warranty"],
    suitableFor: ["إطارات", "بطاريات", "تركيب سريع"],
  }, 26),

  // ── Expanded retail (6) ──
  p({
    id: "retail-coffee-roastery",
    nameAr: "قهوة ومحمصة",
    nameEn: "Coffee Roastery",
    market: "general",
    category: "coffee",
    previewStyle: "warm-retail",
    colors: colors({ primary: "#6b3f2a", accent: "#14b8a6", background: "#fff7ed", foreground: "#24140f", card: "#ffffff", border: "#fed7aa", muted: "#ffedd5", mutedForeground: "#7c2d12" }),
    typography: baseTypography("display"),
    headerStyle: "boutique-compact",
    productCardStyle: "luxury-tall",
    heroStyle: "silk",
    enabledSections: ["hero", "origins", "featured_products", "subscriptions", "brewing_guides"],
    suitableFor: ["قهوة مختصة", "محامص", "اشتراكات"],
  }, 27),
  p({
    id: "retail-organic-grocery",
    nameAr: "بقالة عضوية",
    nameEn: "Organic Grocery",
    market: "general",
    category: "grocery",
    previewStyle: "clean-light",
    colors: colors({ primary: "#15803d", accent: "#facc15", background: "#f7fee7", foreground: "#14532d", card: "#ffffff", border: "#bbf7d0", muted: "#ecfccb", mutedForeground: "#3f6212" }),
    typography: baseTypography(),
    headerStyle: "split-nav",
    productCardStyle: "flat-grid",
    heroStyle: "mesh",
    enabledSections: ["hero", "fresh_categories", "featured_products", "weekly_boxes", "delivery_slots"],
    suitableFor: ["منتجات طازجة", "عضوي", "سلال أسبوعية"],
  }, 28),
  p({
    id: "retail-sports-outdoor",
    nameAr: "رياضة ورحلات",
    nameEn: "Sports & Outdoor",
    market: "general",
    category: "sports",
    previewStyle: "marketplace-grid",
    colors: colors({ primary: "#0f766e", accent: "#f97316", background: "#f8fafc", foreground: "#0f172a", muted: "#e0f2fe" }),
    typography: baseTypography("compact"),
    headerStyle: "showroom-wide",
    productCardStyle: "highlight-price",
    heroStyle: "showroom-banner",
    enabledSections: ["hero", "activity_filters", "featured_products", "bundles", "new_arrivals"],
    suitableFor: ["رياضة", "تخييم", "أدوات رحلات"],
  }, 29),
  p({
    id: "retail-beauty-care",
    nameAr: "تجميل وعناية",
    nameEn: "Beauty Care",
    market: "general",
    category: "beauty",
    previewStyle: "minimal-boutique",
    colors: colors({ primary: "#be123c", accent: "#c084fc", background: "#fff1f2", foreground: "#4c0519", card: "#ffffff", border: "#fecdd3", muted: "#ffe4e6", mutedForeground: "#9f1239" }),
    typography: baseTypography("comfortable"),
    headerStyle: "centered-logo",
    productCardStyle: "rounded-shadow",
    heroStyle: "silk",
    enabledSections: ["hero", "collections", "featured_products", "skin_quiz", "gift_sets"],
    suitableFor: ["عناية", "مكياج", "هدايا جمال"],
  }, 30),
  p({
    id: "retail-books-stationery",
    nameAr: "كتب وقرطاسية",
    nameEn: "Books & Stationery",
    market: "general",
    category: "books_stationery",
    previewStyle: "clean-light",
    colors: colors({ primary: "#334155", accent: "#f59e0b", background: "#f8fafc", foreground: "#0f172a", card: "#ffffff", border: "#cbd5e1", muted: "#e2e8f0", mutedForeground: "#475569" }),
    typography: baseTypography("comfortable"),
    headerStyle: "minimal-sticky",
    productCardStyle: "flat-grid",
    heroStyle: "aurora",
    enabledSections: ["hero", "genres", "featured_products", "school_lists", "author_picks"],
    suitableFor: ["كتب", "مستلزمات مدرسية", "مكاتب"],
  }, 31),
  p({
    id: "retail-flowers-events",
    nameAr: "ورد ومناسبات",
    nameEn: "Flowers & Events",
    market: "general",
    category: "flowers_events",
    previewStyle: "warm-retail",
    colors: colors({ primary: "#be185d", accent: "#22c55e", background: "#fdf2f8", foreground: "#500724", card: "#ffffff", border: "#fbcfe8", muted: "#fce7f3", mutedForeground: "#9d174d" }),
    typography: baseTypography("display"),
    headerStyle: "centered-logo",
    productCardStyle: "luxury-tall",
    heroStyle: "silk",
    enabledSections: ["hero", "occasions", "featured_products", "same_day_delivery", "custom_message"],
    suitableFor: ["ورد", "حفلات", "تغليف هدايا"],
  }, 32),
];

export const THEME_PRESET_MAP = Object.fromEntries(
  THEME_PRESETS.map((t) => [t.id, t]),
) as Record<string, ThemePreset>;

export function getThemePreset(id: string | null | undefined): ThemePreset | undefined {
  if (!id) return undefined;
  return THEME_PRESET_MAP[id];
}

export function listPresetsByMarket(market?: "automotive" | "general" | "all"): ThemePreset[] {
  if (!market || market === "all") return THEME_PRESETS;
  return THEME_PRESETS.filter((t) => t.market === market || t.market === "mixed");
}
